[package]
name = "bridge"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
Sui = { local = "/home/apollo/Apollo/AQY/crates/sui-framework/packages/sui-framework" }

[addresses]
bridge = "0x0"
sui = "0x2"

[dev-dependencies]

[dev-addresses]
